### Initializing Different Types of Arrays

In [1]:
import numpy as np
import sys

In [31]:
# All 0s Matrix
sukablyat = np.zeros((2, 5))
print(sukablyat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [25]:
# All 1s Matrix with Data Type int 8

np.ones((2, 2, 4), dtype="int8")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [28]:
# Initializing Matrices with other numbers
np.full((2, 2), 45, dtype="float64")

array([[45., 45.],
       [45., 45.]])

In [33]:
# Initializing matrices with other numbers (full_like)

np.full_like(sukablyat, 67)

array([[67., 67., 67., 67., 67.],
       [67., 67., 67., 67., 67.]])

In [42]:
# Initializing a matrix of random decimal numbers
np.random.rand(2, 2)
np.random.random_sample(sukablyat.shape)

array([[0.37687041, 0.78042376, 0.06609934, 0.84043906, 0.7193117 ],
       [0.06988305, 0.73761862, 0.71674017, 0.35645007, 0.8012567 ]])

In [64]:
# Initializing a matrix of random integer values
np.random.randint(90, 100, size=(2, 2))

array([[90, 98],
       [93, 93]])

In [67]:
# Identity Matrix

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
# Repeat an array

sukablyat = np.array([[1, 2, 3]])
print(np.repeat(sukablyat, 3, axis = 0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Practice
Initialize the following array with all the techniques above:


```
arr = np.array([[1, 1, 1, 1, 1],
                [1, 0, 0, 0, 1],
                [1, 0, 9, 0, 1],
                [1, 0, 0, 0, 1],
                [1, 1, 1, 1, 1])
```

In [104]:
'''
My thinking process:
2-Dimensional array with 5 rows and 5 columns
First and last rows are just 1s repeated.
Second and fourth rows have both 1s and 0s.
Middle row is like the fourth and second with a 9 in the second index.
'''

sukablyat = np.ones((5, 5), dtype='int8')
sukablyat[1:4, 1:4] = np.zeros((3, 3))
sukablyat[2, 2] = 9
print(sukablyat)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying arrays!

In [110]:
a = np.array([1, 2, 3])
k = a
print(k)

k[0] = 99
print(a)
# So both k and a point to the same array in space, not an actual copy

[1 2 3]
[99  2  3]


In [114]:
# Let's try this again with .copy()

a = np.array([1, 2, 3])
k = a.copy()
k[0] = 99

print(k)
print(a)

[99  2  3]
[1 2 3]


### Let's do some Mathematics ma BOI

In [115]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [125]:
print(a + 5)
print(a - 23)
print(a * 3)
print(a % 2)
print(a ** 2)

# Even trigonometric functions
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 6  7  8  9 10]
[-22 -21 -20 -19 -18]
[ 3  6  9 12 15]
[1 0 1 0 1]
[ 1  4  9 16 25]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [120]:
b = np.array([1, 0, 1, 0, 1])

print(a + b)

[2 2 4 4 6]
