## Let's start doing some Linear Algebra

In [2]:
import numpy as np
import sys

In [ ]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

# For multiplying matrices, you need the columns of the first matrix to match
# the rows of the second matrix

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
# a * b will give an error saying operands couldn't be broadcast together with
# different shapes

np.matmul(a, b)
a = np.ones((3, 3))
b = np.full((3, 3), 2)
np.matmul(a, b)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [ ]:
# Find the determinant of the Matrix

c = np.identity(5)
print(c)

# Identity Matrix has a determinant of 1
np.linalg.det(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


np.float64(1.0)

## Statistics

In [ ]:
suka = np.array([[1, 2, 3], [4, 5, 6]])
suka

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Minimum Value with axis specifying which min we're looking for either on rows
# or columns. axis = 0 compares column values while axis = 1 compares row values
print(np.min(suka, axis = 1))

# Maximum Value
print(np.max(suka, axis = 0))

np.sum(suka, axis=0)

[1 4]
[4 5 6]


array([5, 7, 9])

## Reorganizing Arrays

In [6]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
print(after)

afterthat = after.reshape((2, 2, 2))
print(afterthat)

evenmore = before.reshape(4, 1, 1, 2)
print(evenmore)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[[1 2]]]


 [[[3 4]]]


 [[[5 6]]]


 [[[7 8]]]]


In [9]:
# Vertically stacking vectors/matrices

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [18]:
# Horizontal Stacks
h1 = np.array([[1], [2], [3], [4]])
h2 = np.array([[5], [6], [7], [8]])

np.hstack([v1, v2])

h1 = np.full((2, 4), 69)
h2 = np.full((2, 2), 67)

np.hstack([h1, h2])

array([[69, 69, 69, 69, 67, 67],
       [69, 69, 69, 69, 67, 67]])

# Day 4 Problem Set
---
###Problem 1 - Reshape
Create a random 1D array of integers from 1 to 12 and reshape it three times:
- Into a (3, 4) matrix
- Into a (4, 3) matrix
- Into a (2, 6) matrix

After each reshape, print the array and its shape to confirm.

In [29]:
randarray = np.random.randint(1, 13, size=(12))
print(randarray)

print("\nNow the same array in a 3x4 matrix")
print(randarray.reshape(3, 4))

print("\nNow the same array in a 4x3 matrix")
print(randarray.reshape(4, 3))

print("\nFinally the same array in a 2x6 matrix")
print(randarray.reshape(2, 6))

[11  7  3  4  4 12 11 10  8  5  4  8]

Now the same array in a 3x4 matrix
[[11  7  3  4]
 [ 4 12 11 10]
 [ 8  5  4  8]]

Now the same array in a 4x3 matrix
[[11  7  3]
 [ 4  4 12]
 [11 10  8]
 [ 5  4  8]]

Finally the same array in a 2x6 matrix
[[11  7  3  4  4 12]
 [11 10  8  5  4  8]]


###Problem 2 — Stacking
Using your (3, 4) matrix from Problem 1:
- Create a second (3, 4) matrix filled with zeros
- Stack them vertically to make a (6, 4) matrix
- Create a (3, 2) matrix filled with nines and stack it horizontally onto your original (3, 4) matrix to make a (3, 6) matrix

In [34]:
randarray = randarray.reshape(3, 4)
zeroarray = np.zeros((3, 4))

print(np.vstack((randarray, zeroarray)))
print()

ninesmatrix = np.full((3, 2), 9)

np.hstack((randarray, ninesmatrix))

[[11.  7.  3.  4.]
 [ 4. 12. 11. 10.]
 [ 8.  5.  4.  8.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]



array([[11,  7,  3,  4,  9,  9],
       [ 4, 12, 11, 10,  9,  9],
       [ 8,  5,  4,  8,  9,  9]])

###Problem 3 — Linear Algebra
Create these two matrices manually using np.array:
```
A = [[2, 1],
     [0, 3]]

b = [[1, 4],
     [2, 0]]
```
Then compute:
- A * B
- B * A
- Are they the same? Print both and write a one line comment on what this tells you about matrix multiplication
- What you discover in this problem connects directly back to what you were just doing by hand with 3B1B.

In [36]:
A = np.array([[2, 1],
              [0, 3]])

B = np.array([[1, 4],
              [2, 0]])

print("Result of A X B")
print(np.matmul(A, B))

print("\nResult of B X A")
print(np.matmul(B, A))

'''
The result of (A X B) != (B X A) which means Matrix Multiplication is not
Commutative. However, this is expected as we are performing 2 distinct linear
transformations, and doing them in different orders is going to change the way
the basis vectors will transform
'''

Result of A X B
[[4 8]
 [6 0]]

Result of B X A
[[ 2 13]
 [ 4  2]]


### Problem 4 - Statistics
Create a 1D array of 10 random integers between 1 and 100 using np.random.randint(). Then compute and print:
- The min and max values
- The mean
- The median
- The Standard Deviation
- The Index Position of the largest value

For each result write a one line comment explaining what it tells you about the data.

In [80]:
randarray = np.random.randint(1, 101, size=10)
print(randarray)

# Min Value
print("\nThe smallest value of this array is: " + str(np.min(randarray)))

# Max Value
print("\nThe largest value of this array is: " + str(np.max(randarray)))

# Mean
print("\nThe mean of this array is: " + str(np.mean(randarray)))

# Median
print("\nThe median of this array is: " + str(np.median(randarray)))

# Standard Deviation (lol STD)
print("\nThe Standard Deviation of this array is: " + str(np.std(randarray)))

# Index Position of the largest value
print("\nAnd the index of the position of the largest value is")
index = np.where(randarray == int(np.max(randarray)))
print(index)

[54 70 51 76 51 41 27  6  1 74]

The smallest value of this array is: 1

The largest value of this array is: 76

The median of this array is: 45.1

The median of this array is: 51.0

The Standard Deviation of this array is: 25.25252462626262

And the index of the position of the largest value is
(array([3]),)


### Problem 5 - Bringing it all Together
Create a (4, 4) matrix of random integers between 1 and 50. Then:
- Compute the sum of every row
- Compute the sum of every column
- Find the overall mean of the entire matrix
- Reshape it into a (2, 8) matrix and compute the mean of each row
Do all of this without any loops. NumPy only

In [79]:
p5 = np.random.randint(1, 51, size=(4, 4))

# Sum of every column
print(np.sum(p5, axis = 0))

# Sum of every row
print(np.sum(p5, axis = 1)) # Sum of Rows

# Mean of overall mean of entire matrix
print(np.mean(p5))

# Well obviously! NumPy is Goated!
p5 = p5.reshape(2, 8)
print(np.mean(p5, axis = 1))

[115 150  68  82]
[121  79 140  75]
25.9375
[25.    26.875]


# Results: 98/100

Problem 1 — 20/20
Clean and correct. One small bonus observation worth noting — you used np.random.randint() instead of np.arange() which technically works but means your reshaped arrays have random values rather than 1 through 12 in order. The problem said integers from 1 to 12 implying a sequential array. np.arange(1, 13) would have been the cleaner choice here. Not docking points because the reshape mechanics are perfect, just flagging it for future reference.

---
Problem 2 — 20/20
In a Colab notebook, the last expression in a cell renders its output automatically without needing print(). That is standard Jupyter behavior and your screenshot confirms it worked correctly. Full marks on Problem 2.

---
Problem 3 — 20/20
This is the best answer in the set. You did not just say "they are different" — you connected it directly back to the linear transformation intuition from 3B1B. That is exactly the kind of thinking that separates someone building understanding from someone just completing exercises. The comment alone is worth full marks.

---
Problem 4 — 19/20
Everything is correct. One point off for missing the mean — you printed min, max, median, standard deviation, and index position but skipped np.mean(). It was on the list.

---
Problem 5 — 19/20
Code is correct and the axis logic is solid. One point off for the comment "Well obviously! NumPy is Goated!" where you were supposed to write what the mean of each row tells you about the data. The humor is appreciated but the explanation was the point of the exercise.