In [1]:
import numpy as np

In [2]:
import sys

# The Basics

Day 1:
*   Initializing Arrays, shape, size, data type

In [30]:
# to initialize an array, set up a variable and set it equal to np.array(list)
# how to specify the exact data type of the Array
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [12]:
# 2d Array of Floats
b = np.array([[3.1, 4.2, 5.1], [4.5, 2.5, 8.9]])
print

[[3.1 4.2 5.1]
 [4.5 2.5 8.9]]


In [17]:
# How to get dimensions of your NumPy Arrays
print(a.ndim) # should be 1
print(b.ndim) # should be 2

1
2


In [18]:
# How to get the shape of your NumPy Arrays (which is the vector representation)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [31]:
# How to get the specific data type of the Arrays
print(a.dtype)
print(b.dtype)

int16
float64


In [33]:
# How to get the size of the Array
print(a.itemsize)
print(b.itemsize)

2
8


In [41]:
# How to get total size of the Array = (amount of elements) * size of the Array
print(a.size * a.itemsize)
print(b.size * b.itemsize)

# orrrr

print(a.nbytes)
print(b.nbytes)

6
48
6
48


# The Basics

Day 1:
*   Accessing/Changing specific elements, rows, columns, etc.

In [52]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [66]:
# How to get a specific element from a NumPy Array
# print(arrayname[row index][column index])
print(a[0, 0])
print(a[1, 0])
print(a[1, 5])
print(a[-1, -2])

1
8
13
13


In [61]:
# How to get a specific row
# print(arrayname[row index, :])
  # the : in the second slot stands for all the columns
print(a[0, :])
print(a[1, :])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [64]:
# How to get a specific column
# print(arrayname[:, column index])
  # the : in the first slot stands for all the rows

print(a[:, 0])
print(a[:, 5])

[1 8]
[ 6 13]


In [70]:
# Getting fancier ;) [start index:end index:stepsize]
# get every other element between 2-6 in the a array

print(a[0, 1:6:2])

[2 4 6]


In [73]:
# How to change elements in the NumPy Array
# Doesn't get easier than this brochacho

a[1, 5] = 99
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 99 14]]


In [77]:
# How to replace an entire column in a NumPy Array

a[:, 4] = [72, 73]
print(a)

a[:, 4] = 0
print(a)

[[ 1  2  3  4 72  6  7]
 [ 8  9 10 11 73 99 14]]
[[ 1  2  3  4  0  6  7]
 [ 8  9 10 11  0 99 14]]


In [85]:
# NumPy Array 3-D example

b = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(b)
print(b.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3


In [89]:
# Get a specific element in a 3-D example
# Work Outside In (let's target 6)

# I want the second overarching set so b[1, x, x]. I want the second array of
# the 2 arrays so b[1, 1, x], and I want the first element of the second array
# so finally, b[1, 1, 0] = 6
print(b[1, 1, 0])

6


In [93]:
print(b[:,:,1])

[[1 3]
 [5 7]]


In [97]:
# Replace an element in a 3-D example

b[1,0,:] = 9
b[1,1,:] = [6, 7]
print(b)

b[:,0,:] = [[10, 11], [12, 13]]
print(b)

[[[0 1]
  [2 3]]

 [[9 9]
  [6 7]]]
[[[10 11]
  [ 2  3]]

 [[12 13]
  [ 6  7]]]
