#Day 2 Homework
Yes, I am behind, but I will catch up
- NumPy Notebook: Implement vector addition and scalar multiplication using np.array(). Type every line

In [1]:
import numpy as np

In [2]:
import sys

In [3]:
# Example of 1-D Vector Addition with NumPy

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

vector3 = vector1 + vector2
print(vector3)

[5 7 9]


In [4]:
# Example of 1-D Scalar Multiplication

vector1 = np.array([1, 1, 1])
vector2 = vector1 * 9

print(vector2)

[9 9 9]


Problem 1 — Slicing and Indexing
Given this matrix:

```
pythonA = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])
```

Extract the following without creating a new array manually:
* The second row
* The third column
* The value 50
* The bottom-right 2x2 submatrix

In [26]:
# Problem 2 - My Attempt

pythonA = np.array([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])

# The second row
print(pythonA[1, :])

# The third column
print(pythonA[:, 2])

# The value 50
print(pythonA[1, 1])

# The bottom-right 2x2 submatrix
print(pythonA[1:, 1:])

[40 50 60]
[30 60 90]
50
[[50 60]
 [80 90]]
