#Problem Set - Day 3
---
### Problem 1 - np.zeros() and np.ones()
Create the following without typing any numbers manually:
- A 1D array of 8 zeros
- A 4x4 matrix of all ones with dtype int8
- A 3x5 matrix of all zeros


In [8]:
import numpy as np
import sys

# Create a 1D array of 8 Zeros
arr = np.zeros(8, dtype='int32')
print(arr)

# Create a 4x4 matrix of all ones with data type int8
arr = np.ones((4, 4), dtype='int8')
print(arr)

# Create a 3x5 matrix of all zeros
arr = np.zeros((3, 5), dtype='int8')
print(arr)

[0 0 0 0 0 0 0 0]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Problem 2 — np.full()
Create the following without typing any numbers manually:
- Create a 3x3 matrix where every value is 42
- Create a 1D array of 5 elements all equal to 3.14

In [13]:
# Create a 3x3 matrix where every value is 42
arr = np.full((3, 3), 42)
print(arr)

# Create a 1D array of 5 elements all equal to 3.14
arr = np.full(5, 3.14)
print(arr)

[[42 42 42]
 [42 42 42]
 [42 42 42]]
[3.14 3.14 3.14 3.14 3.14]


### Problem 3 — np.random.rand()
Create the following without typing any numbers manually:
- Generate a 4x4 matrix of random floats between 0 and 1
- Generate a 1D array of 10 random floats
- Run the cell twice and observe what happens — why do the values change each time?

In [43]:
# Generate a 4x4 matrix of random floats between 0 and 1
arr = np.random.rand(4, 4)
print(arr)

# Generate a 1D array of 10 random floats
arr = np.random.rand(10)
print(arr)

'''
Why are the values changing each time?

The reason is that we are constantly calling a random function which has new
numbers enter the function every time we call on it. Similar to constantly
rolling a die, new numbers will always be selected for each index of the arrays.
'''

[[0.44841677 0.88662277 0.13110293 0.22808245]
 [0.66106269 0.67949559 0.59079252 0.5294922 ]
 [0.02729682 0.93223932 0.03474899 0.02895175]
 [0.87932452 0.53753954 0.36390727 0.78909693]]
[0.42579757 0.01016286 0.56725598 0.64702313 0.72266703 0.17277135
 0.91783682 0.8895991  0.12827736 0.04235043]


'\nWhy are the values changing each time?\n\nThe reason is that we are constantly calling a random function which has new\nnumbers enter the function every time we call on it. Similar to constantly \nrolling a die, new numbers will always be selected for each index of the arrays.\n'

### Problem 4 — The Border Challenge
Inspired by your FreeCodeCamp exercise. Build this array using only np.ones(), np.zeros(), and slicing — no np.array() allowed:
```
[[1, 1, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 1],
 [1, 1, 1, 1, 1, 1]]
```

In [48]:
a = np.ones((4, 6), dtype='int8')
a[1:3, 1:5] = np.zeros((2, 4), dtype='int8')
print(a)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


### Problem 5 — Combining Everything
Build this array using only initialization functions and slicing:
```
[[7, 7, 7, 7],
 [7, 0, 0, 7],
 [7, 5, 5, 7],
 [7, 7, 7, 7]]
```

In [56]:
a = np.full((4, 4), 7)
a[1, 1:3] = np.zeros(2)
a[2, 1:3] = np.full(2, 5)
print(a)

[[7 7 7 7]
 [7 0 0 7]
 [7 5 5 7]
 [7 7 7 7]]


###Homework Result: 99/100

#### Problem 1 — 20/20
Perfect. You even added dtype='int8' on the zeros matrix without being asked, showing you are thinking about memory and data types proactively. That is a good instinct to keep.

---
####Problem 2 — 20/20
Clean. You handled both integer and float values without flinching. Nothing to add.

---
####Problem 3 — 19/20
Code is perfect. Your explanation of why values change is correct in spirit but missing the precise term. The reason is that np.random.rand() uses a pseudo-random number generator with ***no fixed seed***. If you wrote np.random.seed(42) before the call, the output would be identical every time you ran it. That concept — seeding for reproducibility — comes up constantly in ML research when you need experiments to be repeatable. One point off for not getting there.

---
####Problem 4 — 20/20
Excellent. Clean slice, correct dimensions, built it exactly right.

---
####Problem 5 — 20/20
Your solution for Problem 5 was completely correct and the best way to write it. There is nothing to change.